/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Multisend } from "./Multisend";
export type { TRLOOP } from "./TRLOOP";
export type { Vesting } from "./Vesting";
