/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace Multisend {
  export type TransferItemStruct = {
    recipient: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
  };

  export type TransferItemStructOutput = [string, BigNumber] & {
    recipient: string;
    amount: BigNumber;
  };
}

export interface MultisendInterface extends utils.Interface {
  functions: {
    "batchTransfer(address,(address,uint256)[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "batchTransfer"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "batchTransfer",
    values: [PromiseOrValue<string>, Multisend.TransferItemStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchTransfer",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Multisend extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MultisendInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    batchTransfer(
      _token: PromiseOrValue<string>,
      _transfers: Multisend.TransferItemStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  batchTransfer(
    _token: PromiseOrValue<string>,
    _transfers: Multisend.TransferItemStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    batchTransfer(
      _token: PromiseOrValue<string>,
      _transfers: Multisend.TransferItemStruct[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    batchTransfer(
      _token: PromiseOrValue<string>,
      _transfers: Multisend.TransferItemStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    batchTransfer(
      _token: PromiseOrValue<string>,
      _transfers: Multisend.TransferItemStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
